version: '3.8'

services:
    c1:
      image: react-app:v0
      build: ./socle-react/
      ports:
        - 4001:80
      # depends_on:
      #   - nginx
    c2: 
      image: vue-app:v0
      build: ./socle-vue/vue-app/
      ports:
        - 4003:80
      # depends_on:
      #   - nginx



    # database:
    #     container_name: database
    #     image: mysql:8.0
    #     command: --default-authentication-plugin=mysql_native_password
    #     environment:
    #       MYSQL_ROOT_PASSWORD: secret
    #       MYSQL_DATABASE: symfony_docker
    #       MYSQL_USER: symfony
    #       MYSQL_PASSWORD: symfony
    #     ports:
    #       - '4306:3306'
    #     volumes:
    #       - ./mysql:/var/lib/mysql

    php:
        container_name: projectsymfonyphp
        build:
          context: ./php
        ports:
          - '9000:9000'
        volumes:
          - ./app:/var/www/symfony_docker
        # depends_on:
        #   - database


    nginx:
        container_name: projectnnginx
        image: nginx:1.21-alpine
        ports:
          - '8080:80'
        volumes:
          - ./app:/var/www/symfony_docker
          - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
          - php
